# Base image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./

RUN npm install

# Copy the rest of the app
COPY . .

# Use a build-time argument instead of a hard-coded ENV variable
ARG REACT_APP_BACKEND_URL

RUN REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL npm run build



# Install serve globally
RUN npm install -g serve

# Expose the port serve will use
EXPOSE 5000

# Serve the build folder
CMD ["serve", "-s", "build", "-l", "5000"]

